name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # CI Job - Continuous Integration
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.25'

      - name: Run tests
        run: go test -v

      - name: Build app
        run: go build -o app main.go

  # CD Job - Continuous Deployment
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.25'

      - name: Build for deployment
        run: go build -o app main.go

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/simple-go-app:latest"

      - name: Deploy (simulation)
        run: |
          echo "Docker image pushed: ${{ secrets.DOCKERHUB_USERNAME }}/simple-go-app:latest"
